django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from perfis import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfis.urls')),
    path('', include('usuarios.urls')),
]

perfis/urls.py
from django.urls import path, re_path, include
from . import views
from rest_framework.routers import DefaultRouter
from perfis import views
from rest_framework.authtoken import views as auth_views

router = DefaultRouter()
router.register('perfis', views.PerfilViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('perfil/', views.get_meu_perfil, name='perfil'),
    path('convites/', views.get_convites, name='convites'),
    path('convites/convidar/<int:perfil_id>', views.convidar, name='convidar'),
    path('convites/aceitar/<int:convite_id>', views.aceitar, name='aceitar'),
    path('login/', auth_views.obtain_auth_token, name='login'),
]

usuarios/urls.py
from unicodedata import name
from django.urls import path
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('registrar/', RegistrarUsuarioView.as_view(), name="registrar"),
    path('login/', LoginView.as_view(template_name='login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True

        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Porfavor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuário já existente')
            valid = False
        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS,
                                         forms.utils.ErrorList())
        errors.append(message)

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm
# Create your views here.


class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        #preenche o form
        form = RegistrarUsuarioForm(request.POST)

        #verifica se é valido
        if form.is_valid():
            dados_form = form.data

            #cria o usuário
            usuario = User.objects.create_user(dados_form['nome'],
                                               dados_form['email'],
                                               dados_form['senha'])

            #cria o perfil
            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)

            #grava no banco
            perfil.save()

            #redireciona para index
            return redirect('index')
        return render(request, self.template_name, {'form': form})

usuarios/templates/base_usuario.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width"/>
        <title>ExperienceIn</title>

        <link href="{% static 'styles/bootstrap.css'%}" rel="stylesheet"/>
        <link href="{% static 'styles/signin.css'%}" rel="stylesheet"/>
    </head>

    <body>
        <div class="container">
            {% block body%}

            {% endblock%}
        </div>
    </body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus/>
        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha"/>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
        <input type="hidden" name="next" value="{{next}}"/>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p> Por favor, verifique o Email e/ou Senha informados </p>
            </div>
        {% endif %}

        <a href="{% url 'registrar' %}"> Registre-se</a>
    </form>
{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}

{% block body %}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading"> Crie seu usuário</h2>

        <input type="text" id="id_email" name="email" value="{{form.email.value}}" class="form-control" placeholder="Email *" required autofocus/>
        <input type="text" id="id_id_nome" name="nome" value="{{form.nome.value}}" class="form-control" placeholder="Nome *" required/>
        <input type="password" id="id_senha" name="senha" value="{{form.senha.value}}" class="form-control" placeholder="Senha*" required/>
        <hr/>
        <input type="text" id="id_telefone" name="telefone" value="{{form.telefone.value}}" class="form-control" placeholder="Telefone"/>
        <input type="text" id="id_nome_empresa" name="nome_empresa" value="{{form.nome_empresa.value}}" class="form-control" placeholder="Empresa"/>
        <hr/>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login"> Regitrar</button>
        
        <!-- if novo aqui -->
        <hr/>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="buton", class="close" data-dismiss="alert" aria-hidden="true">$times;</button>
                {{form.non_field_errors}}
            </div>
        {% endif%}
        <!-- fim if novo -->
    </form>
{% endblock%}